wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1674138553.369758
    t:
      1:
      - 1
      - 50
      - 55
      - 77
      2:
      - 1
      - 50
      - 55
      - 77
      3:
      - 1
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 3
      - 5
