numpy
pandas
hydra-core
hydra
python-dotenv==0.21.0
python_arango==7.5.5
PyYAML==6.0
requests==2.28.1
torch_geometric==2.2.0
torch-tb-profiler==0.4.1
torchvision==0.14.1
tqdm==4.64.1
pytest
google-api-core
google-auth
google-auth-oauthlib
google-cloud-core
google-cloud-storage
google-crc32c
google-resumable-media
googleapis-common-protos
